#+title: ITS 2022-08-22

* bis 600€

| Case Min 2 Lüfter | Antec VSK3000B Midi Tower | 37€  |
| Mainboard:        | MSI B450-A Pro MAX AMD    | 60€  |
| Memory 16GBs+ :   | Corsair                   | 60€  |
| CPU:              | AMD RYZEN 5600G           | 160€ |
| SSD:              | GIGABYTE NVMe SSD 256 GB  | 30€  |
| Video Card:       | MSI GTX1630 Ventus        | 180€ |
| Power supply:     | 500 Watt LC-Power LC500H  | 30€  |
| DVD Drive         | ASUS DRW-24D5MT           | 15€  |
| lan cable 10m     | Sharkoon                  | 7€   |
| Mouse + Keyboard  | Trust Taro                | 15€  |
| OS                | Kubuntu? Oo               | 0€   |
| Office            | Libre Office              | 0€   |
| Power strip       | cheap                     | 5€   |
|                   |                           |      |
| Gesamt            |                           | 599€ |


* Erläuterung:
** Gehäuse
2 Lüfter um auch bei hohen Temperaturen kühlung zu gewähren
** Mainboard
günstiges gerät von qualitativ gutem Hersteller für möglichst lange Lebensdauer
** Memory
16gb sind mindestens für Eplan empfohlen
** CPU
möglichst viel Leistung zu günstigem Preis
** SSD
Speicher ist für professionelle Anwendung ziemlich klein, 500gb für 20€ mehr vermutlich eine gute Idee
** Video Card
Eplan empfielt eine 4gb Karte mit Leistung grob jenseits der gtx760. Hier gibt es nur wenige verfügbare Modelle. Aktuelle Preise sind immer noch übertrieben.
** Power Suply
sehr günstiges 500W Netzteil, würde gerne ein etwas hochwertigeres verbauen
** DVD, Kabel, Maus, Tastatur
das billigste vim Billigen, sollte aber ausreichen.
** Office
Microsoft Office alleine kostet ca. 200€ und ist daher beim 600€ Budget raus.
** OS
Windows würde auch nochmal ca 150€ Kosten. Und unter Linux läuft Eplan nicht. Wenn diese 150€ auch noch gespart werden sollen wird Eplan wahrscheinlich kaum noch brauchbar laufen.
Anscheinend ist es möflich Eplan mit Hilfe von Wine unter Linux zum laufen zu bringen, ist aber wahrscheinlich für professionelle Anwendung nicht stabil und performant genug.

* Sonstiges
- Energiesparend und vor allem Leise sind ein Luxus den man sich bei dem Preis nicht leisten kann.
- Ein Mac System ist bei dem Preisrahmen nicht drin. Eplan läuft außerdem auch nur mit Hilfe einer Virtuellen Maschine.
- Eplan kostet Tausende € für eine Lizens bzw. 125€/Benutzer im Monat. Ich glaube da würde es sich lohnen ein paar € mehr für den Arbeitsplatz in die Hand zu nehmen.
